# **Module 2 讀取與選擇 Melboune Housing**

In [ ]:
import pandas as pd
melbourne_file_path = './sample_data/melb_data.csv'
melbourne_data = pd.read_csv(melbourne_file_path)

#印出所有欄位
print(melbourne_data.columns)

#讀取Price欄
melbourne_price_data = melbourne_data.Price
print(melbourne_price_data.head())

#任取兩欄
columns_of_interest = ['Landsize', 'BuildingArea']
two_columns_of_data = melbourne_data[columns_of_interest]
two_columns_of_data.describe()

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')
0    1480000.0
1    1035000.0
2    1465000.0
3     850000.0
4    1600000.0
Name: Price, dtype: float64

           Landsize  BuildingArea
count   6808.000000   3817.000000
mean     456.953290    145.449830
std     1336.263109    158.486262
min        0.000000      0.000000
25%      130.000000     88.000000
50%      336.000000    122.000000
75%      616.000000    170.000000
max    75100.000000   6791.000000

# **Module 2 Read Gapminder CSV and selection**

In [ ]:
import pandas as pd
# data_url a CSV file
data_url = 'http://bit.ly/2cLzoxH'
# read data from url as pandas dataframe
gapminder = pd.read_csv(data_url)

#設定選擇判準
is_2002 =  gapminder['year']==2002

#DF 只讀year==2002資料
gapminder_2002 = gapminder[is_2002]

#Pandas Chaining
gapminder_2002 = gapminder[gapminder.year.eq(2002)]

#過濾Null資料
gapminder_no_NA = gapminder[gapminder.year.notnull()]

#只選擇years 在 list [1952, 2007]中的rows
years = [1952, 2007]
gapminder.year.isin(years)

gapminder_years= gapminder[gapminder.year.isin(years)]
print("gapminder_years.shape:", gapminder_years.shape)

#Unique value
gapminder_years.year.unique()

#多重條件
continents = ['Asia','Africa', 'Americas', 'Europe']
gapminder_Ocean = gapminder[~gapminder.continent.isin(continents)]
print("gapminder_ocean.shape: ", gapminder_Ocean.shape) 
gapminder[~gapminder.continent.isin(continents) & 
           gapminder.year.isin(years)]

gapminder_years.shape: (284, 6)
gapminder_ocean.shape:  (24, 6)

          country  year         pop continent  lifeExp    gdpPercap
60      Australia  1952   8691212.0   Oceania   69.120  10039.59564
71      Australia  2007  20434176.0   Oceania   81.235  34435.36744
1092  New Zealand  1952   1994794.0   Oceania   69.390  10556.57566
1103  New Zealand  2007   4115771.0   Oceania   80.204  25185.00911

# **Module 2 Pandas JSON**

In [ ]:
import pandas as pd
df = pd.DataFrame([['a','b'], ['c','d']], index=['row 1', 'row 2'], columns=['col 1', 'col 2']) 
df.to_json(orient='split')

'{"columns":["col 1","col 2"],"index":["row 1","row 2"],"data":[["a","b"],["c","d"]]}'

In [ ]:
pd.read_json(_, orient='split')

      col 1 col 2
row 1     a     b
row 2     c     d

In [ ]:
df.to_json(orient='index')

'{"row 1":{"col 1":"a","col 2":"b"},"row 2":{"col 1":"c","col 2":"d"}}'

In [ ]:
pd.read_json(_, orient='index')

      col 1 col 2
row 1     a     b
row 2     c     d

In [ ]:
df.to_json(orient='records')

'[{"col 1":"a","col 2":"b"},{"col 1":"c","col 2":"d"}]'

In [ ]:
pd.read_json(_, orient='records')

  col 1 col 2
0     a     b
1     c     d

In [ ]:
df.to_json(orient='table')

'{"schema":{"fields":[{"name":"index","type":"string"},{"name":"col 1","type":"string"},{"name":"col 2","type":"string"}],"primaryKey":["index"],"pandas_version":"0.20.0"},"data":[{"index":"row 1","col 1":"a","col 2":"b"},{"index":"row 2","col 1":"c","col 2":"d"}]}'

In [ ]:
pd.read_json(_, orient='table')

      col 1 col 2
row 1     a     b
row 2     c     d

In [ ]:
import json
result=df.to_json(orient='table')
parsed = json.loads(result)
json.dumps(parsed, indent=4)

'{\n    "schema": {\n        "fields": [\n            {\n                "name": "index",\n                "type": "string"\n            },\n            {\n                "name": "col 1",\n                "type": "string"\n            },\n            {\n                "name": "col 2",\n                "type": "string"\n            }\n        ],\n        "primaryKey": [\n            "index"\n        ],\n        "pandas_version": "0.20.0"\n    },\n    "data": [\n        {\n            "index": "row 1",\n            "col 1": "a",\n            "col 2": "b"\n        },\n        {\n            "index": "row 2",\n            "col 1": "c",\n            "col 2": "d"\n        }\n    ]\n}'

# **Module 3 文字與時間資料處理**

In [ ]:
import numpy as np
pd.Series(['a', 'b', 'c'])
s=pd.Series(['a', 'b', 'c'], dtype="string")
s.astype("string")
s2 = pd.Series(['a_b_c', 'c_d_e', np.nan, 'f_g_h'], dtype="string")
s2.str.split('_')

0    [a, b, c]
1    [c, d, e]
2         <NA>
3    [f, g, h]
dtype: object

In [ ]:
t = pd.Series(['a', 'b', np.nan, 'd'], dtype="string")
t.str.cat(sep=',')

'a,b,d'

In [ ]:
t.str.cat(sep=',', na_rep='-')

'a,b,-,d'

In [ ]:
pd.Series(range(3), index=pd.date_range('2000', freq='D', periods=3))

2000-01-01    0
2000-01-02    1
2000-01-03    2
Freq: D, dtype: int64

In [ ]:
friday = pd.Timestamp('2018-01-05')
saturday = friday + pd.Timedelta('1 day')
saturday

Timestamp('2018-01-06 00:00:00')

In [ ]:
saturday.day_name()

'Saturday'

In [ ]:
idx = pd.date_range('2018-01-01', periods=5, freq='H')
ts = pd.Series(range(len(idx)), index=idx)
ts

2018-01-01 00:00:00    0
2018-01-01 01:00:00    1
2018-01-01 02:00:00    2
2018-01-01 03:00:00    3
2018-01-01 04:00:00    4
Freq: H, dtype: int64

In [ ]:
ts.resample('2H').mean()

2018-01-01 00:00:00    0.5
2018-01-01 02:00:00    2.5
2018-01-01 04:00:00    4.0
Freq: 2H, dtype: float64

In [ ]:
import datetime
pd.Timestamp(datetime.datetime(2012, 5, 1))

Timestamp('2012-05-01 00:00:00')

In [ ]:
pd.Period('2012-05', freq='D')

Period('2012-05-01', 'D')

In [ ]:
dates = [pd.Timestamp('2012-05-01'),
   ....:          pd.Timestamp('2012-05-02'),
   ....:          pd.Timestamp('2012-05-03')]
   ....: 
ts = pd.Series(np.random.randn(3), dates)
type(ts.index)

pandas.core.indexes.datetimes.DatetimeIndex

In [ ]:
ts.index

DatetimeIndex(['2012-05-01', '2012-05-02', '2012-05-03'], dtype='datetime64[ns]', freq=None)

In [ ]:
ts

2012-05-01   -0.016915
2012-05-02   -1.609899
2012-05-03    0.946186
dtype: float64

# **Module 4 Merge and Join 資料合併與重塑**

In [ ]:
d = {'lkey': ['foo', 'bar', 'baz', 'foo'], 'value': [1,2,3,4]}
A = pd.DataFrame(data=d)
A

  lkey  value
0  foo      1
1  bar      2
2  baz      3
3  foo      4

In [ ]:
d = {'rkey': ['foo', 'bar', 'qux', 'bar'], 'value': [5,6,7,8]}
B = pd.DataFrame(data=d)
B

  rkey  value
0  foo      5
1  bar      6
2  qux      7
3  bar      8

In [ ]:
# Outer Join
A.merge(B, left_on='lkey', right_on='rkey', how='outer')

  lkey  value_x rkey  value_y
0  foo      1.0  foo      5.0
1  foo      4.0  foo      5.0
2  bar      2.0  bar      6.0
3  bar      2.0  bar      8.0
4  baz      3.0  NaN      NaN
5  NaN      NaN  qux      7.0

In [ ]:
# Inner Join
A.merge(B, left_on='lkey', right_on='rkey', how='inner')

  lkey  value_x rkey  value_y
0  foo        1  foo        5
1  foo        4  foo        5
2  bar        2  bar        6
3  bar        2  bar        8

In [ ]:
# Left Join
A.merge(B, left_on='lkey', right_on='rkey', how='left')

  lkey  value_x rkey  value_y
0  foo        1  foo      5.0
1  bar        2  bar      6.0
2  bar        2  bar      8.0
3  baz        3  NaN      NaN
4  foo        4  foo      5.0

In [ ]:
# Right Join
A.merge(B, left_on='lkey', right_on='rkey', how='right')

  lkey  value_x rkey  value_y
0  foo      1.0  foo        5
1  foo      4.0  foo        5
2  bar      2.0  bar        6
3  bar      2.0  bar        8
4  NaN      NaN  qux        7

# **Join based on Index**

In [ ]:
#join based on index
A.join(B, lsuffix='_l', rsuffix='_r', how='outer')

  lkey  value_l rkey  value_r
0  foo        1  foo        5
1  bar        2  bar        6
2  baz        3  qux        7
3  foo        4  bar        8